services:
  db:
    image: mariadb
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=fluga # creates table flflugauag
      - MYSQL_USER=user # creates user user'
      - MYSQL_PASSWORD=password # password for the user 
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
